serverAddr = "47.122.130.157"
serverPort = 7000
auth.method = "token"
auth.token = "212060gj"

[[proxies]]
name = "i3_nas"
type = "http"
localIP = "10.20.60.194"  
localPort = 5000
subdomain = ["nas"]

[[proxies]]
name = "i3_ssh"
type = "tcp"
localIP = "10.20.60.194"
localPort = 9878
remotePort = 19878

[[proxies]]
name = "i3_饥荒面板"
type = "tcp"
localIP = "127.0.0.1"
localPort = 8082
remotePort = 18082
